'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Check, Database, Eye, Fingerprint, Globe2, LockKeyhole, ShieldCheck, Smartphone } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { useApp } from '@/context/AppContext';
import type { Language } from '@/types';

const steps=['Welcome','Language','Verify','Goals','Connect','Understand','Ready'];
const inference=['Reading your transaction patterns…','Understanding recurring commitments…','Estimating financial resilience…','Building your financial state…'];

export default function OnboardingPage(){
  const router=useRouter(); const {language,setLanguage,setIsOnboarded,setPersona}=useApp(); const [step,setStep]=useState(0); const [mobile,setMobile]=useState('98765 43210'); const [otp,setOtp]=useState('123456'); const [goals,setGoals]=useState(['Build emergency fund']); const [inferenceStep,setInferenceStep]=useState(0);
  useEffect(()=>{if(step!==5)return; const timer=setInterval(()=>setInferenceStep(v=>{if(v>=inference.length-1){clearInterval(timer);setTimeout(()=>setStep(6),500);return v}return v+1}),650);return()=>clearInterval(timer)},[step]);
  const next=()=>setStep(v=>Math.min(6,v+1)); const back=()=>setStep(v=>Math.max(0,v-1));
  return <div className="min-h-[calc(100vh-72px)] bg-[#071a17] text-[#fffaf0]">
    <div className="grid min-h-[calc(100vh-72px)] lg:grid-cols-[.42fr_.58fr]">
      <aside className="grid-rule noise hidden border-r border-white/10 p-10 lg:flex lg:flex-col lg:justify-between"><div className="relative z-10"><p className="eyebrow !text-[#e88a34]">Financial intelligence for Bharat</p><h1 className="mt-6 text-5xl font-medium leading-[.98] tracking-[-.06em]">A financial life is more than a balance.</h1><p className="mt-6 text-sm leading-6 text-white/42">Connect the patterns. Establish purpose. Make every insight explainable.</p></div><div className="relative z-10"><div className="space-y-4">{steps.map((s,i)=><div key={s} className={`flex items-center gap-3 text-xs ${i===step?'text-white':i<step?'text-[#75bca5]':'text-white/25'}`}><span className={`grid h-6 w-6 place-items-center border ${i===step?'border-[#e88a34] text-[#e88a34]':i<step?'border-[#2d7a65]':'border-white/10'}`}>{i<step?<Check className="h-3 w-3"/>:<span className="font-financial text-[9px]">0{i+1}</span>}</span>{s}</div>)}</div></div></aside>
      <section className="flex items-center justify-center p-5 md:p-10"><div className="w-full max-w-2xl">
        <div className="mb-8 flex items-center gap-2 lg:hidden">{steps.map((_,i)=><span key={i} className={`h-1 flex-1 ${i<=step?'bg-[#e88a34]':'bg-white/10'}`}/>)}</div>
        <AnimatePresence mode="wait">
          {step===0&&<Panel key="welcome" icon={<Eye/>} eyebrow="Welcome to ARTHDRISHTI" title="Your financial life, ready to be understood." copy="This guided demo uses deterministic local data. No bank credentials or real money movement is involved."><button onClick={next} className="primary-action">Begin with Ravi <ArrowRight className="h-4 w-4"/></button></Panel>}
          {step===1&&<Panel key="language" icon={<Globe2/>} eyebrow="Language" title="How should ARTHDRISHTI speak with you?" copy="Choose any language now. You can switch at any time."><div className="grid gap-3 sm:grid-cols-3">{([['en','English'],['hi','हिंदी'],['hinglish','Hinglish']] as [Language,string][]).map(([id,label])=><button key={id} onClick={()=>setLanguage(id)} className={`border p-5 text-left ${language===id?'border-[#e88a34] bg-[#e88a34]/10':'border-white/12'}`}><span className="text-lg">{label}</span><span className="mt-2 block text-[10px] uppercase tracking-wider text-white/30">{id}</span></button>)}</div><Nav back={back} next={next}/></Panel>}
          {step===2&&<Panel key="verify" icon={<Smartphone/>} eyebrow="Demo authentication" title="Verify your mobile number." copy="The number and OTP are pre-filled for this offline demo. Existing demo authentication is preserved."><label className="block"><span className="micro-label !text-white/30">Mobile number</span><div className="mt-3 flex border border-white/15"><span className="border-r border-white/15 p-4 text-sm text-white/45">+91</span><input value={mobile} onChange={e=>setMobile(e.target.value)} className="flex-1 bg-transparent p-4 outline-none"/></div></label><label className="mt-5 block"><span className="micro-label !text-white/30">One-time password</span><input value={otp} onChange={e=>setOtp(e.target.value)} inputMode="numeric" className="font-financial mt-3 w-full border border-white/15 bg-transparent p-4 tracking-[.6em] outline-none"/></label><p className="mt-3 text-[10px] text-white/25">Demo OTP: 123456</p><Nav back={back} next={next}/></Panel>}
          {step===3&&<Panel key="goals" icon={<Fingerprint/>} eyebrow="Financial intent" title="What should ARTHDRISHTI help protect?" copy="Intent shapes recommendations. It never becomes a product sales target."><div className="grid gap-3 sm:grid-cols-2">{['Build emergency fund','Reduce debt pressure','Plan a major purchase','Understand spending'].map(g=><button key={g} onClick={()=>setGoals(v=>v.includes(g)?v.filter(x=>x!==g):[...v,g])} className={`flex items-center justify-between border p-4 text-left text-sm ${goals.includes(g)?'border-[#e88a34] bg-[#e88a34]/8':'border-white/12 text-white/55'}`}>{g}{goals.includes(g)&&<Check className="h-4 w-4 text-[#e88a34]"/>}</button>)}</div><Nav back={back} next={next}/></Panel>}
          {step===4&&<Panel key="connect" icon={<Database/>} eyebrow="Connect financial data" title="One demo source. Four explicit purposes." copy="The deterministic Ravi fixture simulates 6 months of transaction, income, EMI and savings history."><div className="border border-white/12">{[['Transactions','Spending intelligence'],['Income','Health and affordability'],['EMI & debt','Suitability'],['Savings','Liquidity and resilience']].map(([a,b])=><div key={a} className="flex items-center justify-between border-b last:border-b-0 border-white/10 p-4"><div><p className="text-sm">{a}</p><p className="mt-1 text-[10px] text-white/30">{b}</p></div><Check className="h-4 w-4 text-[#75bca5]"/></div>)}</div><div className="mt-5 flex gap-3 border-l-2 border-[#e88a34] bg-white/[.035] p-4"><LockKeyhole className="h-4 w-4 shrink-0 text-[#e88a34]"/><p className="text-[11px] leading-5 text-white/38">By continuing, you enable these purposes for the demo. Optional consent can be revoked later.</p></div><Nav back={back} next={next} label="Connect demo data"/></Panel>}
          {step===5&&<Panel key="understand" icon={<Eye/>} eyebrow="Understanding your financial life" title={inference[inferenceStep]} copy="The intelligence pipeline is deterministic, local and available without an AI API."><div className="mt-10 space-y-4">{inference.map((text,i)=><div key={text} className={`flex items-center gap-4 text-sm ${i<=inferenceStep?'text-white':'text-white/18'}`}><span className={`grid h-7 w-7 place-items-center border ${i<inferenceStep?'border-[#2d7a65] bg-[#2d7a65]/20 text-[#75bca5]':i===inferenceStep?'border-[#e88a34] text-[#e88a34]':'border-white/10'}`}>{i<inferenceStep?<Check className="h-3.5 w-3.5"/>:<span className={i===inferenceStep?'h-1.5 w-1.5 rounded-full bg-[#e88a34] breathe':''}/>}</span>{text}</div>)}</div></Panel>}
          {step===6&&<Panel key="ready" icon={<ShieldCheck/>} eyebrow="ARTHDRISHTI ready" title="Your financial life is ready." copy="Ravi’s current state is tightening. The first priority is protection and recovery—not another product."><div className="grid grid-cols-3 gap-px bg-white/10 border border-white/10">{[['Health','64/100'],['Buffer','2.4 mo'],['Priority','Recover']].map(([a,b])=><div key={a} className="bg-[#071a17] p-4"><p className="micro-label !text-white/25">{a}</p><p className="font-financial mt-3 text-lg">{b}</p></div>)}</div><button onClick={()=>{setPersona('ravi');setIsOnboarded(true);router.push('/dashboard')}} className="primary-action mt-8">Open financial home <ArrowRight className="h-4 w-4"/></button></Panel>}
        </AnimatePresence>
      </div></section>
    </div>
    <style jsx global>{`.primary-action{display:inline-flex;align-items:center;gap:.75rem;background:#e88a34;color:#10211d;padding:.9rem 1.25rem;font-size:.7rem;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.primary-action:hover{background:#f0a05a}`}</style>
  </div>;
}

function Panel({icon,eyebrow,title,copy,children}:{icon:React.ReactNode;eyebrow:string;title:string;copy:string;children:React.ReactNode}){return <motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.35}}><span className="grid h-12 w-12 place-items-center border border-[#e88a34]/35 bg-[#e88a34]/8 text-[#e88a34]">{icon}</span><p className="eyebrow mt-8 !text-[#e88a34]">{eyebrow}</p><h2 className="mt-5 text-4xl font-medium leading-[1.02] tracking-[-.05em] md:text-5xl">{title}</h2><p className="mt-5 mb-8 max-w-xl text-sm leading-6 text-white/42">{copy}</p>{children}</motion.section>}
function Nav({back,next,label='Continue'}:{back:()=>void;next:()=>void;label?:string}){return <div className="mt-8 flex items-center justify-between border-t border-white/10 pt-6"><button onClick={back} className="flex items-center gap-2 text-xs text-white/40"><ArrowLeft className="h-4 w-4"/>Back</button><button onClick={next} className="primary-action">{label}<ArrowRight className="h-4 w-4"/></button></div>}
