'use client';

import { Search, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import { PageHeader } from '@/components/FinancialVisuals';
import { formatINR, getDemoState } from '@/data/intelligence';
import type { DemoScenario, PersonaId } from '@/types';

const cases:Array<[PersonaId,DemoScenario,string]>=[['ravi','stable','Ravi · Stable'],['ravi','tightening','Ravi · Tightening'],['ravi','stress','Ravi · Stress'],['ravi','anomaly','Ravi · Anomaly'],['ananya','growth','Ananya · Growth'],['ananya','stable','Ananya · Stable'],['ananya','tightening','Ananya · Tightening'],['ananya','stress','Ananya · Stress'],['ananya','anomaly','Ananya · Anomaly']];

export default function CustomersPage(){
  const [query,setQuery]=useState(''); const [risk,setRisk]=useState('all');
  const rows=useMemo(()=>cases.map(([p,s,label])=>({label,...getDemoState(p,s)})).filter(r=>r.label.toLowerCase().includes(query.toLowerCase())&&(risk==='all'||r.financialState.risk.level===risk)),[query,risk]);
  return <div><PageHeader eyebrow="Demo · Intelligence matrix" title="One architecture. Meaningfully different outcomes." description="A demo-facing matrix of deterministic customer states. Sensitive transaction detail stays in the customer experience." aside={<p className="font-financial text-3xl">{rows.length} <span className="text-xs text-muted-foreground">states</span></p>}/>
    <div className="page-wrap py-8"><div className="surface mb-6 flex flex-col sm:flex-row"><label className="flex h-14 flex-1 items-center gap-3 px-4"><Search className="h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer or scenario…" className="w-full bg-transparent text-sm outline-none"/></label><label className="flex h-14 items-center gap-3 border-t hairline px-4 sm:border-l sm:border-t-0"><SlidersHorizontal className="h-4 w-4 text-muted-foreground"/><select value={risk} onChange={e=>setRisk(e.target.value)} className="bg-transparent text-xs font-semibold outline-none"><option value="all">All risk bands</option><option value="low">Low</option><option value="moderate">Moderate</option><option value="elevated">Elevated</option><option value="high">High</option></select></label></div>
      <div className="grid gap-4 md:hidden">{rows.map(r=>{const s=r.financialState;return <article key={r.label} className="surface p-5"><div className="flex items-start justify-between gap-4"><h2 className="font-semibold">{r.label}</h2><span className={`text-xs font-semibold capitalize ${s.risk.level==='high'||s.risk.level==='elevated'?'text-[#b84f49]':s.risk.level==='low'?'text-[#2d7a65]':'text-[#a46020]'}`}>{s.risk.level} risk</span></div><dl className="mt-5 grid grid-cols-2 gap-x-5 gap-y-4 border-y hairline py-5">{[['Income',formatINR(s.income.monthly)],['Savings rate',`${s.savings.rate}%`],['Buffer',`${s.savings.bufferMonths} mo`],['EMI burden',`${s.debt.emiBurdenRatio}%`],['Utilization',`${s.debt.utilization}%`],['Cash flow',s.cashFlow.trend],['Health',String(s.healthScore)],['Anomaly',r.scenario==='anomaly'?'Review':'Clear'],['Suitability',s.healthScore>80?'Growth ready':'Protect / recover'],['Consent','Active']].map(([a,b])=><div key={a}><dt className="micro-label">{a}</dt><dd className="font-financial mt-2 text-sm capitalize">{b}</dd></div>)}</dl><div className="mt-5"><p className="micro-label">Recommended action</p><p className="mt-2 text-sm font-medium">{r.recommendations[0].title}</p><p className="mt-3 text-[10px] uppercase tracking-wider text-muted-foreground">EN · HI · Hing</p></div></article>})}</div>
      <div className="hidden overflow-x-auto border border-border bg-card md:block"><table className="w-full min-w-[1200px] border-collapse text-left"><thead><tr className="bg-[#e9e3d8] text-[9px] uppercase tracking-[.14em] text-muted-foreground">{['Customer state','Income','Savings rate','Buffer','EMI burden','Utilization','Cash flow','Health','Risk','Anomaly','Recommended action','Suitability','Language','Consent'].map(h=><th key={h} className="border-b hairline px-4 py-4 font-bold">{h}</th>)}</tr></thead><tbody>{rows.map(r=>{const s=r.financialState;return <tr key={r.label} className="interactive-row border-b last:border-b-0 hairline text-xs"><td className="px-4 py-4 font-semibold">{r.label}</td><td className="font-financial px-4">{formatINR(s.income.monthly)}</td><td className="font-financial px-4">{s.savings.rate}%</td><td className="font-financial px-4">{s.savings.bufferMonths} mo</td><td className="font-financial px-4">{s.debt.emiBurdenRatio}%</td><td className="font-financial px-4">{s.debt.utilization}%</td><td className="capitalize px-4">{s.cashFlow.trend}</td><td className="font-financial px-4">{s.healthScore}</td><td className={`capitalize px-4 font-semibold ${s.risk.level==='high'||s.risk.level==='elevated'?'text-[#b84f49]':s.risk.level==='low'?'text-[#2d7a65]':'text-[#a46020]'}`}>{s.risk.level}</td><td className="px-4">{r.scenario==='anomaly'?'Review':'Clear'}</td><td className="px-4">{r.recommendations[0].title}</td><td className="px-4">{s.healthScore>80?'Growth ready':'Protect / recover'}</td><td className="px-4">EN · HI · Hing</td><td className="px-4 text-[#2d7a65]">Active</td></tr>})}</tbody></table></div>
    </div></div>;
}
