'use client';

import Link from 'next/link';
import { ArrowRight, BrainCircuit, Database, FileSearch, ShieldCheck } from 'lucide-react';
import { DecisionMark, PageHeader, PrototypeNote } from '@/components/FinancialVisuals';
import { useApp } from '@/context/AppContext';
import { formatINR } from '@/lib/format';

export default function ExplainPage(){
  const {demoState}=useApp(); const s=demoState.financialState; const a=demoState.loanAssessment;
  const flow=[['Customer data','Consent-scoped transaction, income, debt and savings signals'],['Feature engineering','EMI burden, buffer, cash-flow trend and behavioural deltas'],['Financial state',`Health ${s.healthScore} · Risk ${s.risk.level} · Buffer ${s.savings.bufferMonths} months`],['Risk & affordability models',`Financial resilience ${demoState.modelInference.score} · ${a.affordabilityBand} affordability`],['Decision engine',`Projected EMI burden ${a.affordabilityRatio}%`],['Governance',a.recommendation.replaceAll('_',' ')],['Explanation','Numbers, consequences and a safer alternative']];
  return <div>
    <PageHeader eyebrow="Trust · Explainability" title="Every important answer should survive the question: why?" description="Inspect the data, features, inference, policy checks, projected impact and alternative behind a financial decision." aside={<DecisionMark decision={a.recommendation}/>} />
    <section className="surface-dark grid-rule py-12"><div className="page-wrap">
      <div className="mb-9 flex items-end justify-between"><div><p className="eyebrow !text-[#e88a34]">Model inference trace</p><h2 className="mt-4 text-3xl font-medium tracking-[-.045em]">From customer data to controlled explanation</h2></div><BrainCircuit className="hidden h-8 w-8 text-[#e88a34] md:block"/></div>
      <div className="grid gap-px border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-7">{flow.map(([a,b],i)=><div key={a} className="relative bg-[#071a17] p-5"><span className="font-financial text-[10px] text-[#e88a34]">0{i+1}</span><h3 className="mt-6 text-sm font-semibold">{a}</h3><p className="mt-3 text-[11px] leading-5 text-white/38">{b}</p>{i<flow.length-1&&<ArrowRight className="absolute -right-2.5 top-8 z-10 hidden h-5 w-5 rounded-full bg-[#102b26] p-1 text-[#e88a34] lg:block"/>}</div>)}</div>
    </div></section>
    <section className="page-section"><div className="page-wrap grid gap-8 lg:grid-cols-[1fr_1fr]">
      <div className="surface p-6 md:p-8"><div className="flex items-center gap-3"><FileSearch className="h-5 w-5 text-[#e88a34]"/><p className="eyebrow">Why was the ₹5L loan not recommended?</p></div><dl className="mt-7">{[['Monthly income',formatINR(s.income.monthly)],['Existing EMI',formatINR(s.debt.existingEmi)],['Current burden',`${s.debt.emiBurdenRatio}%`],['Additional EMI',formatINR(a.monthlyEmi)],['Projected burden',`${a.affordabilityRatio}%`],['Emergency buffer',`${s.savings.bufferMonths} months`],['Cash flow',s.cashFlow.trend]].map(([x,y])=><div key={x} className="flex items-center justify-between border-b hairline py-4 text-sm"><dt className="text-muted-foreground">{x}</dt><dd className="font-financial font-medium capitalize">{y}</dd></div>)}</dl><div className="mt-7 border-l-2 border-[#b84f49] bg-[#b84f49]/8 p-5"><p className="micro-label text-[#b84f49]">Conclusion</p><p className="mt-3 text-lg font-semibold">Not recommended right now.</p><p className="mt-2 text-xs leading-5 text-muted-foreground">The obligation would materially increase debt pressure while the buffer is below target.</p></div></div>
      <div className="space-y-5"><div className="surface p-6 md:p-8"><div className="flex items-center gap-3"><Database className="h-5 w-5 text-[#e88a34]"/><p className="eyebrow">Feature contributions</p></div><div className="mt-7 space-y-5">{demoState.modelInference.contributions.map(c=><div key={c.feature}><div className="flex justify-between text-xs"><span>{c.feature}</span><div className="flex gap-4"><span className="font-financial text-muted-foreground">{c.value}</span><b className={`font-financial ${c.impact>0?'text-[#2d7a65]':'text-[#b84f49]'}`}>{c.impact>0?'+':''}{c.impact}</b></div></div><div className="mt-2 flex h-1.5 items-stretch bg-secondary"><div className="ml-1/2 bg-border"/><div className={`h-full ${c.impact>0?'bg-[#2d7a65]':'bg-[#b84f49]'}`} style={{width:`${Math.abs(c.impact)*2.3}%`,marginLeft:c.impact>0?'50%':`${50-Math.abs(c.impact)*2.3}%`}}/></div></div>)}</div></div><PrototypeNote/><Link href="/governance" className="flex items-center justify-between bg-[#102b26] p-5 text-white"><span className="flex items-center gap-3 text-sm font-semibold"><ShieldCheck className="h-5 w-5 text-[#e88a34]"/>Inspect the governance policy</span><ArrowRight className="h-4 w-4"/></Link></div>
    </div></section>
  </div>;
}
